/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateDetectionTemplateRequest,
  DeleteDetectionTemplateParams,
  EditDetectionTemplateRequest,
  GetDetectionTemplatesParams,
} from "@/types/api";

import { orvalAxiosInstance } from "@/lib/orval-axios";
import type { ErrorType, BodyType } from "@/lib/orval-axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getDetectionTemplates = (
  params?: GetDetectionTemplatesParams,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<Blob>(
    { url: `/rules`, method: "GET", params, responseType: "blob", signal },
    options,
  );
};

export const getGetDetectionTemplatesInfiniteQueryKey = (params?: GetDetectionTemplatesParams) => {
  return ["infinite", "getDetectionTemplates", ...(params ? [params] : [])] as const;
};

export const getGetDetectionTemplatesQueryKey = (params?: GetDetectionTemplatesParams) => {
  return ["getDetectionTemplates", ...(params ? [params] : [])] as const;
};

export const getGetDetectionTemplatesInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getDetectionTemplates>>>,
  TError = ErrorType<unknown>,
>(
  params?: GetDetectionTemplatesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDetectionTemplates>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDetectionTemplatesInfiniteQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDetectionTemplates>>> = ({ signal }) =>
    getDetectionTemplates(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getDetectionTemplates>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDetectionTemplatesInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDetectionTemplates>>
>;
export type GetDetectionTemplatesInfiniteQueryError = ErrorType<unknown>;

export function useGetDetectionTemplatesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getDetectionTemplates>>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetDetectionTemplatesParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDetectionTemplates>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDetectionTemplates>>,
          TError,
          Awaited<ReturnType<typeof getDetectionTemplates>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDetectionTemplatesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getDetectionTemplates>>>,
  TError = ErrorType<unknown>,
>(
  params?: GetDetectionTemplatesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDetectionTemplates>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDetectionTemplates>>,
          TError,
          Awaited<ReturnType<typeof getDetectionTemplates>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDetectionTemplatesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getDetectionTemplates>>>,
  TError = ErrorType<unknown>,
>(
  params?: GetDetectionTemplatesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDetectionTemplates>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetDetectionTemplatesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getDetectionTemplates>>>,
  TError = ErrorType<unknown>,
>(
  params?: GetDetectionTemplatesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDetectionTemplates>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetDetectionTemplatesInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetDetectionTemplatesQueryOptions = <
  TData = Awaited<ReturnType<typeof getDetectionTemplates>>,
  TError = ErrorType<unknown>,
>(
  params?: GetDetectionTemplatesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDetectionTemplates>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDetectionTemplatesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDetectionTemplates>>> = ({ signal }) =>
    getDetectionTemplates(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDetectionTemplates>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDetectionTemplatesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDetectionTemplates>>
>;
export type GetDetectionTemplatesQueryError = ErrorType<unknown>;

export function useGetDetectionTemplates<
  TData = Awaited<ReturnType<typeof getDetectionTemplates>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetDetectionTemplatesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDetectionTemplates>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDetectionTemplates>>,
          TError,
          Awaited<ReturnType<typeof getDetectionTemplates>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDetectionTemplates<
  TData = Awaited<ReturnType<typeof getDetectionTemplates>>,
  TError = ErrorType<unknown>,
>(
  params?: GetDetectionTemplatesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDetectionTemplates>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDetectionTemplates>>,
          TError,
          Awaited<ReturnType<typeof getDetectionTemplates>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDetectionTemplates<
  TData = Awaited<ReturnType<typeof getDetectionTemplates>>,
  TError = ErrorType<unknown>,
>(
  params?: GetDetectionTemplatesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDetectionTemplates>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetDetectionTemplates<
  TData = Awaited<ReturnType<typeof getDetectionTemplates>>,
  TError = ErrorType<unknown>,
>(
  params?: GetDetectionTemplatesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDetectionTemplates>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetDetectionTemplatesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const editDetectionTemplate = (
  editDetectionTemplateRequest: BodyType<EditDetectionTemplateRequest>,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<Blob>(
    {
      url: `/rules`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: editDetectionTemplateRequest,
      responseType: "blob",
      signal,
    },
    options,
  );
};

export const getEditDetectionTemplateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof editDetectionTemplate>>,
    TError,
    { data: BodyType<EditDetectionTemplateRequest> },
    TContext
  >;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof editDetectionTemplate>>,
  TError,
  { data: BodyType<EditDetectionTemplateRequest> },
  TContext
> => {
  const mutationKey = ["editDetectionTemplate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof editDetectionTemplate>>,
    { data: BodyType<EditDetectionTemplateRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return editDetectionTemplate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EditDetectionTemplateMutationResult = NonNullable<
  Awaited<ReturnType<typeof editDetectionTemplate>>
>;
export type EditDetectionTemplateMutationBody = BodyType<EditDetectionTemplateRequest>;
export type EditDetectionTemplateMutationError = ErrorType<unknown>;

export const useEditDetectionTemplate = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof editDetectionTemplate>>,
      TError,
      { data: BodyType<EditDetectionTemplateRequest> },
      TContext
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof editDetectionTemplate>>,
  TError,
  { data: BodyType<EditDetectionTemplateRequest> },
  TContext
> => {
  return useMutation(getEditDetectionTemplateMutationOptions(options), queryClient);
};

export const addDetectionTemplate = (
  createDetectionTemplateRequest: BodyType<CreateDetectionTemplateRequest>,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<Blob>(
    {
      url: `/rules`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createDetectionTemplateRequest,
      responseType: "blob",
      signal,
    },
    options,
  );
};

export const getAddDetectionTemplateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addDetectionTemplate>>,
    TError,
    { data: BodyType<CreateDetectionTemplateRequest> },
    TContext
  >;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addDetectionTemplate>>,
  TError,
  { data: BodyType<CreateDetectionTemplateRequest> },
  TContext
> => {
  const mutationKey = ["addDetectionTemplate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addDetectionTemplate>>,
    { data: BodyType<CreateDetectionTemplateRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return addDetectionTemplate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddDetectionTemplateMutationResult = NonNullable<
  Awaited<ReturnType<typeof addDetectionTemplate>>
>;
export type AddDetectionTemplateMutationBody = BodyType<CreateDetectionTemplateRequest>;
export type AddDetectionTemplateMutationError = ErrorType<unknown>;

export const useAddDetectionTemplate = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addDetectionTemplate>>,
      TError,
      { data: BodyType<CreateDetectionTemplateRequest> },
      TContext
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addDetectionTemplate>>,
  TError,
  { data: BodyType<CreateDetectionTemplateRequest> },
  TContext
> => {
  return useMutation(getAddDetectionTemplateMutationOptions(options), queryClient);
};

export const getDetectedElements = (
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<Blob>(
    { url: `/rules/elements`, method: "GET", responseType: "blob", signal },
    options,
  );
};

export const getGetDetectedElementsInfiniteQueryKey = () => {
  return ["infinite", "getDetectedElements"] as const;
};

export const getGetDetectedElementsQueryKey = () => {
  return ["getDetectedElements"] as const;
};

export const getGetDetectedElementsInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getDetectedElements>>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDetectedElements>>, TError, TData>
  >;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDetectedElementsInfiniteQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDetectedElements>>> = ({ signal }) =>
    getDetectedElements(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getDetectedElements>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDetectedElementsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDetectedElements>>
>;
export type GetDetectedElementsInfiniteQueryError = ErrorType<unknown>;

export function useGetDetectedElementsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getDetectedElements>>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDetectedElements>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDetectedElements>>,
          TError,
          Awaited<ReturnType<typeof getDetectedElements>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDetectedElementsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getDetectedElements>>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDetectedElements>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDetectedElements>>,
          TError,
          Awaited<ReturnType<typeof getDetectedElements>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDetectedElementsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getDetectedElements>>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDetectedElements>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetDetectedElementsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getDetectedElements>>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDetectedElements>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetDetectedElementsInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetDetectedElementsQueryOptions = <
  TData = Awaited<ReturnType<typeof getDetectedElements>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDetectedElements>>, TError, TData>>;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDetectedElementsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDetectedElements>>> = ({ signal }) =>
    getDetectedElements(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDetectedElements>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDetectedElementsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDetectedElements>>
>;
export type GetDetectedElementsQueryError = ErrorType<unknown>;

export function useGetDetectedElements<
  TData = Awaited<ReturnType<typeof getDetectedElements>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDetectedElements>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDetectedElements>>,
          TError,
          Awaited<ReturnType<typeof getDetectedElements>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDetectedElements<
  TData = Awaited<ReturnType<typeof getDetectedElements>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDetectedElements>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDetectedElements>>,
          TError,
          Awaited<ReturnType<typeof getDetectedElements>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDetectedElements<
  TData = Awaited<ReturnType<typeof getDetectedElements>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDetectedElements>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetDetectedElements<
  TData = Awaited<ReturnType<typeof getDetectedElements>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDetectedElements>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetDetectedElementsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const deleteDetectionTemplate = (
  params: DeleteDetectionTemplateParams,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<Blob>(
    { url: `/rules/`, method: "DELETE", params, responseType: "blob", signal },
    options,
  );
};

export const getDeleteDetectionTemplateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteDetectionTemplate>>,
    TError,
    { params: DeleteDetectionTemplateParams },
    TContext
  >;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteDetectionTemplate>>,
  TError,
  { params: DeleteDetectionTemplateParams },
  TContext
> => {
  const mutationKey = ["deleteDetectionTemplate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteDetectionTemplate>>,
    { params: DeleteDetectionTemplateParams }
  > = (props) => {
    const { params } = props ?? {};

    return deleteDetectionTemplate(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteDetectionTemplateMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteDetectionTemplate>>
>;

export type DeleteDetectionTemplateMutationError = ErrorType<unknown>;

export const useDeleteDetectionTemplate = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteDetectionTemplate>>,
      TError,
      { params: DeleteDetectionTemplateParams },
      TContext
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteDetectionTemplate>>,
  TError,
  { params: DeleteDetectionTemplateParams },
  TContext
> => {
  return useMutation(getDeleteDetectionTemplateMutationOptions(options), queryClient);
};
