/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { UploadVideo200, VideoSequence, VideoSequencePage } from "../../../types/api";

export const getUploadVideoResponseMock = (): UploadVideo200 => ({});

export const getGetVideosResponseMock = (): ArrayBuffer => ({});

export const getGetVideoMediaResponseMock = (
  overrideResponse: Partial<Extract<ArrayBuffer, object>> = {},
): ArrayBuffer => ({
  resource: faker.helpers.arrayElement([
    new ArrayBuffer(faker.number.int({ min: 1, max: 64 })),
    undefined,
  ]),
  position: faker.helpers.arrayElement([faker.number.int(), undefined]),
  count: faker.helpers.arrayElement([faker.number.int(), undefined]),
  ...overrideResponse,
});

export const getDeleteVideoResponseMock = (): ArrayBuffer => ({});

export const getGetVideoDashManifestResponseMock = (): string => faker.word.sample();

export const getGetVideoInfoResponseMock = (): ArrayBuffer => ({});

export const getGetVideoDashAssetResponseMock = (): ArrayBuffer => ({});

export const getGetVideoSequencesResponseMock = (
  overrideResponse: Partial<Extract<VideoSequencePage, object>> = {},
): VideoSequencePage => ({
  content: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
    () => ({
      origin_id: faker.string.uuid(),
      sequence_upload_date: faker.date.past().toISOString().slice(0, 19) + "Z",
      parts: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
        () => ({
          id: faker.string.uuid(),
          name: faker.string.alpha({ length: { min: 10, max: 20 } }),
          description: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            null,
          ]),
          upload_date: faker.date.past().toISOString().slice(0, 19) + "Z",
          continuation_of: faker.helpers.arrayElement([faker.string.uuid(), null]),
        }),
      ),
    }),
  ),
  page: {
    size: faker.number.int(),
    number: faker.number.int(),
    totalElements: faker.number.int(),
    totalPages: faker.number.int(),
  },
  ...overrideResponse,
});

export const getGetVideoSequenceResponseMock = (
  overrideResponse: Partial<Extract<VideoSequence, object>> = {},
): VideoSequence => ({
  origin_id: faker.string.uuid(),
  sequence_upload_date: faker.date.past().toISOString().slice(0, 19) + "Z",
  parts: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.string.uuid(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    description: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    upload_date: faker.date.past().toISOString().slice(0, 19) + "Z",
    continuation_of: faker.helpers.arrayElement([faker.string.uuid(), null]),
  })),
  ...overrideResponse,
});

export const getGetSequenceManifestResponseMock = (): string => faker.word.sample();

export const getGetVideoSequenceInfoResponseMock = (): ArrayBuffer => ({});

export const getGetSequenceDashAssetResponseMock = (): ArrayBuffer => ({});

export const getDeleteVideoSequenceResponseMock = (): ArrayBuffer => ({});

export const getUploadVideoMockHandler = (
  overrideResponse?:
    | UploadVideo200
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<UploadVideo200> | UploadVideo200),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/videos/upload",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      const resolvedBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getUploadVideoResponseMock();
      const textBody =
        typeof resolvedBody === "string" ? resolvedBody : JSON.stringify(resolvedBody ?? null);
      return HttpResponse.text(textBody, { status: 200 });
    },
    options,
  );
};

export const getGetVideosMockHandler = (
  overrideResponse?:
    | ArrayBuffer
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ArrayBuffer> | ArrayBuffer),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/videos",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      const binaryBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetVideosResponseMock();
      return HttpResponse.arrayBuffer(
        binaryBody instanceof ArrayBuffer ? binaryBody : new ArrayBuffer(0),
        { status: 200, headers: { "Content-Type": "application/octet-stream" } },
      );
    },
    options,
  );
};

export const getGetVideoMediaMockHandler = (
  overrideResponse?:
    | ArrayBuffer
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ArrayBuffer> | ArrayBuffer),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/videos/:fileIdentifier",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      const binaryBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetVideoMediaResponseMock();
      return HttpResponse.arrayBuffer(
        binaryBody instanceof ArrayBuffer ? binaryBody : new ArrayBuffer(0),
        { status: 200, headers: { "Content-Type": "application/octet-stream" } },
      );
    },
    options,
  );
};

export const getDeleteVideoMockHandler = (
  overrideResponse?:
    | ArrayBuffer
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<ArrayBuffer> | ArrayBuffer),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/videos/:fileIdentifier",
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      const binaryBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getDeleteVideoResponseMock();
      return HttpResponse.arrayBuffer(
        binaryBody instanceof ArrayBuffer ? binaryBody : new ArrayBuffer(0),
        { status: 200, headers: { "Content-Type": "application/octet-stream" } },
      );
    },
    options,
  );
};

export const getGetVideoDashManifestMockHandler = (
  overrideResponse?:
    | string
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<string> | string),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/videos/:fileIdentifier/manifest.mpd",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      const resolvedBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetVideoDashManifestResponseMock();
      const textBody =
        typeof resolvedBody === "string" ? resolvedBody : JSON.stringify(resolvedBody ?? null);
      return HttpResponse.xml(textBody, { status: 200 });
    },
    options,
  );
};

export const getGetVideoInfoMockHandler = (
  overrideResponse?:
    | ArrayBuffer
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ArrayBuffer> | ArrayBuffer),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/videos/:fileIdentifier/info",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      const binaryBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetVideoInfoResponseMock();
      return HttpResponse.arrayBuffer(
        binaryBody instanceof ArrayBuffer ? binaryBody : new ArrayBuffer(0),
        { status: 200, headers: { "Content-Type": "application/octet-stream" } },
      );
    },
    options,
  );
};

export const getGetVideoDashAssetMockHandler = (
  overrideResponse?:
    | ArrayBuffer
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ArrayBuffer> | ArrayBuffer),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/videos/:fileIdentifier/dash/:assetPath",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      const binaryBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetVideoDashAssetResponseMock();
      return HttpResponse.arrayBuffer(
        binaryBody instanceof ArrayBuffer ? binaryBody : new ArrayBuffer(0),
        { status: 200, headers: { "Content-Type": "application/octet-stream" } },
      );
    },
    options,
  );
};

export const getGetVideoSequencesMockHandler = (
  overrideResponse?:
    | VideoSequencePage
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<VideoSequencePage> | VideoSequencePage),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/videos/sequences",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetVideoSequencesResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetVideoSequenceMockHandler = (
  overrideResponse?:
    | VideoSequence
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<VideoSequence> | VideoSequence),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/videos/sequences/:originId",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetVideoSequenceResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetSequenceManifestMockHandler = (
  overrideResponse?:
    | string
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<string> | string),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/videos/sequences/:originId/manifest.mpd",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      const resolvedBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetSequenceManifestResponseMock();
      const textBody =
        typeof resolvedBody === "string" ? resolvedBody : JSON.stringify(resolvedBody ?? null);
      return HttpResponse.xml(textBody, { status: 200 });
    },
    options,
  );
};

export const getGetVideoSequenceInfoMockHandler = (
  overrideResponse?:
    | ArrayBuffer
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ArrayBuffer> | ArrayBuffer),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/videos/sequences/:originId/info",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      const binaryBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetVideoSequenceInfoResponseMock();
      return HttpResponse.arrayBuffer(
        binaryBody instanceof ArrayBuffer ? binaryBody : new ArrayBuffer(0),
        { status: 200, headers: { "Content-Type": "application/octet-stream" } },
      );
    },
    options,
  );
};

export const getGetSequenceDashAssetMockHandler = (
  overrideResponse?:
    | ArrayBuffer
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ArrayBuffer> | ArrayBuffer),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/videos/sequences/:originId/dash/:videoId/:assetPath",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      const binaryBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetSequenceDashAssetResponseMock();
      return HttpResponse.arrayBuffer(
        binaryBody instanceof ArrayBuffer ? binaryBody : new ArrayBuffer(0),
        { status: 200, headers: { "Content-Type": "application/octet-stream" } },
      );
    },
    options,
  );
};

export const getDeleteVideoSequenceMockHandler = (
  overrideResponse?:
    | ArrayBuffer
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<ArrayBuffer> | ArrayBuffer),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/videos/sequences/:fileIdentifier",
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      const binaryBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getDeleteVideoSequenceResponseMock();
      return HttpResponse.arrayBuffer(
        binaryBody instanceof ArrayBuffer ? binaryBody : new ArrayBuffer(0),
        { status: 200, headers: { "Content-Type": "application/octet-stream" } },
      );
    },
    options,
  );
};
export const getOpenAPIDefinitionMock = () => [
  getUploadVideoMockHandler(),
  getGetVideosMockHandler(),
  getGetVideoMediaMockHandler(),
  getDeleteVideoMockHandler(),
  getGetVideoDashManifestMockHandler(),
  getGetVideoInfoMockHandler(),
  getGetVideoDashAssetMockHandler(),
  getGetVideoSequencesMockHandler(),
  getGetVideoSequenceMockHandler(),
  getGetSequenceManifestMockHandler(),
  getGetVideoSequenceInfoMockHandler(),
  getGetSequenceDashAssetMockHandler(),
  getDeleteVideoSequenceMockHandler(),
];
