/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

export const getGetDetectionTemplatesResponseMock = (): ArrayBuffer => ({});

export const getEditDetectionTemplateResponseMock = (): ArrayBuffer => ({});

export const getAddDetectionTemplateResponseMock = (): ArrayBuffer => ({});

export const getGetDetectedElementsResponseMock = (): ArrayBuffer => ({});

export const getDeleteDetectionTemplateResponseMock = (): ArrayBuffer => ({});

export const getGetDetectionTemplatesMockHandler = (
  overrideResponse?:
    | ArrayBuffer
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ArrayBuffer> | ArrayBuffer),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/rules",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      const binaryBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetDetectionTemplatesResponseMock();
      return HttpResponse.arrayBuffer(
        binaryBody instanceof ArrayBuffer ? binaryBody : new ArrayBuffer(0),
        { status: 200, headers: { "Content-Type": "application/octet-stream" } },
      );
    },
    options,
  );
};

export const getEditDetectionTemplateMockHandler = (
  overrideResponse?:
    | ArrayBuffer
    | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<ArrayBuffer> | ArrayBuffer),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    "*/rules",
    async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
      const binaryBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getEditDetectionTemplateResponseMock();
      return HttpResponse.arrayBuffer(
        binaryBody instanceof ArrayBuffer ? binaryBody : new ArrayBuffer(0),
        { status: 200, headers: { "Content-Type": "application/octet-stream" } },
      );
    },
    options,
  );
};

export const getAddDetectionTemplateMockHandler = (
  overrideResponse?:
    | ArrayBuffer
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ArrayBuffer> | ArrayBuffer),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/rules",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      const binaryBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getAddDetectionTemplateResponseMock();
      return HttpResponse.arrayBuffer(
        binaryBody instanceof ArrayBuffer ? binaryBody : new ArrayBuffer(0),
        { status: 200, headers: { "Content-Type": "application/octet-stream" } },
      );
    },
    options,
  );
};

export const getGetDetectedElementsMockHandler = (
  overrideResponse?:
    | ArrayBuffer
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ArrayBuffer> | ArrayBuffer),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/rules/elements",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      const binaryBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetDetectedElementsResponseMock();
      return HttpResponse.arrayBuffer(
        binaryBody instanceof ArrayBuffer ? binaryBody : new ArrayBuffer(0),
        { status: 200, headers: { "Content-Type": "application/octet-stream" } },
      );
    },
    options,
  );
};

export const getDeleteDetectionTemplateMockHandler = (
  overrideResponse?:
    | ArrayBuffer
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<ArrayBuffer> | ArrayBuffer),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/rules/",
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      const binaryBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getDeleteDetectionTemplateResponseMock();
      return HttpResponse.arrayBuffer(
        binaryBody instanceof ArrayBuffer ? binaryBody : new ArrayBuffer(0),
        { status: 200, headers: { "Content-Type": "application/octet-stream" } },
      );
    },
    options,
  );
};
export const getOpenAPIDefinitionMock = () => [
  getGetDetectionTemplatesMockHandler(),
  getEditDetectionTemplateMockHandler(),
  getAddDetectionTemplateMockHandler(),
  getGetDetectedElementsMockHandler(),
  getDeleteDetectionTemplateMockHandler(),
];
