/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { ForbiddenZoneRequest } from "../../../types/api";

import { orvalAxiosInstance } from "../../../lib/orval-axios";
import type { ErrorType, BodyType } from "../../../lib/orval-axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const updateZone = (
  id: number,
  forbiddenZoneRequest: BodyType<ForbiddenZoneRequest>,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<Blob>(
    {
      url: `/zones/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: forbiddenZoneRequest,
      responseType: "blob",
      signal,
    },
    options,
  );
};

export const getUpdateZoneMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateZone>>,
    TError,
    { id: number; data: BodyType<ForbiddenZoneRequest> },
    TContext
  >;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateZone>>,
  TError,
  { id: number; data: BodyType<ForbiddenZoneRequest> },
  TContext
> => {
  const mutationKey = ["updateZone"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateZone>>,
    { id: number; data: BodyType<ForbiddenZoneRequest> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateZone(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateZoneMutationResult = NonNullable<Awaited<ReturnType<typeof updateZone>>>;
export type UpdateZoneMutationBody = BodyType<ForbiddenZoneRequest>;
export type UpdateZoneMutationError = ErrorType<unknown>;

export const useUpdateZone = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateZone>>,
      TError,
      { id: number; data: BodyType<ForbiddenZoneRequest> },
      TContext
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateZone>>,
  TError,
  { id: number; data: BodyType<ForbiddenZoneRequest> },
  TContext
> => {
  return useMutation(getUpdateZoneMutationOptions(options), queryClient);
};

export const deleteZone = (
  id: number,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<void>({ url: `/zones/${id}`, method: "DELETE", signal }, options);
};

export const getDeleteZoneMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteZone>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteZone>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteZone"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteZone>>, { id: number }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return deleteZone(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteZoneMutationResult = NonNullable<Awaited<ReturnType<typeof deleteZone>>>;

export type DeleteZoneMutationError = ErrorType<unknown>;

export const useDeleteZone = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteZone>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteZone>>, TError, { id: number }, TContext> => {
  return useMutation(getDeleteZoneMutationOptions(options), queryClient);
};

export const getZones = (
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<Blob>(
    { url: `/zones`, method: "GET", responseType: "blob", signal },
    options,
  );
};

export const getGetZonesInfiniteQueryKey = () => {
  return ["infinite", "getZones"] as const;
};

export const getGetZonesQueryKey = () => {
  return ["getZones"] as const;
};

export const getGetZonesInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getZones>>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getZones>>, TError, TData>>;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetZonesInfiniteQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getZones>>> = ({ signal }) =>
    getZones(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getZones>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetZonesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getZones>>>;
export type GetZonesInfiniteQueryError = ErrorType<unknown>;

export function useGetZonesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getZones>>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getZones>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getZones>>,
          TError,
          Awaited<ReturnType<typeof getZones>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetZonesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getZones>>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getZones>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getZones>>,
          TError,
          Awaited<ReturnType<typeof getZones>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetZonesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getZones>>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getZones>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetZonesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getZones>>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getZones>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetZonesInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetZonesQueryOptions = <
  TData = Awaited<ReturnType<typeof getZones>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getZones>>, TError, TData>>;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetZonesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getZones>>> = ({ signal }) =>
    getZones(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getZones>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetZonesQueryResult = NonNullable<Awaited<ReturnType<typeof getZones>>>;
export type GetZonesQueryError = ErrorType<unknown>;

export function useGetZones<
  TData = Awaited<ReturnType<typeof getZones>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getZones>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getZones>>,
          TError,
          Awaited<ReturnType<typeof getZones>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetZones<
  TData = Awaited<ReturnType<typeof getZones>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getZones>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getZones>>,
          TError,
          Awaited<ReturnType<typeof getZones>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetZones<
  TData = Awaited<ReturnType<typeof getZones>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getZones>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetZones<
  TData = Awaited<ReturnType<typeof getZones>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getZones>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetZonesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const createZone = (
  forbiddenZoneRequest: BodyType<ForbiddenZoneRequest>,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<Blob>(
    {
      url: `/zones`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: forbiddenZoneRequest,
      responseType: "blob",
      signal,
    },
    options,
  );
};

export const getCreateZoneMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createZone>>,
    TError,
    { data: BodyType<ForbiddenZoneRequest> },
    TContext
  >;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createZone>>,
  TError,
  { data: BodyType<ForbiddenZoneRequest> },
  TContext
> => {
  const mutationKey = ["createZone"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createZone>>,
    { data: BodyType<ForbiddenZoneRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createZone(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateZoneMutationResult = NonNullable<Awaited<ReturnType<typeof createZone>>>;
export type CreateZoneMutationBody = BodyType<ForbiddenZoneRequest>;
export type CreateZoneMutationError = ErrorType<unknown>;

export const useCreateZone = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createZone>>,
      TError,
      { data: BodyType<ForbiddenZoneRequest> },
      TContext
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createZone>>,
  TError,
  { data: BodyType<ForbiddenZoneRequest> },
  TContext
> => {
  return useMutation(getCreateZoneMutationOptions(options), queryClient);
};
