/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

export const getUpdateZoneResponseMock = (
  overrideResponse: Partial<Extract<ArrayBuffer, object>> = {},
): ArrayBuffer => ({
  id: faker.helpers.arrayElement([faker.number.int(), undefined]),
  name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  policy: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  points: faker.helpers.arrayElement([
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
      Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
        faker.number.float({ fractionDigits: 2 }),
      ),
    ),
    undefined,
  ]),
  active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  reference_video_id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
  aspect_ratio: faker.helpers.arrayElement([faker.number.float({ fractionDigits: 2 }), undefined]),
  ...overrideResponse,
});

export const getGetZonesResponseMock = (): ArrayBuffer =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.helpers.arrayElement([faker.number.int(), undefined]),
    name: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    policy: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    points: faker.helpers.arrayElement([
      Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
        Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
          faker.number.float({ fractionDigits: 2 }),
        ),
      ),
      undefined,
    ]),
    active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    reference_video_id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
    aspect_ratio: faker.helpers.arrayElement([
      faker.number.float({ fractionDigits: 2 }),
      undefined,
    ]),
  }));

export const getCreateZoneResponseMock = (
  overrideResponse: Partial<Extract<ArrayBuffer, object>> = {},
): ArrayBuffer => ({
  id: faker.helpers.arrayElement([faker.number.int(), undefined]),
  name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  policy: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  points: faker.helpers.arrayElement([
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
      Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
        faker.number.float({ fractionDigits: 2 }),
      ),
    ),
    undefined,
  ]),
  active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  reference_video_id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
  aspect_ratio: faker.helpers.arrayElement([faker.number.float({ fractionDigits: 2 }), undefined]),
  ...overrideResponse,
});

export const getUpdateZoneMockHandler = (
  overrideResponse?:
    | ArrayBuffer
    | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<ArrayBuffer> | ArrayBuffer),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    "*/zones/:id",
    async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
      const binaryBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getUpdateZoneResponseMock();
      return HttpResponse.arrayBuffer(
        binaryBody instanceof ArrayBuffer ? binaryBody : new ArrayBuffer(0),
        { status: 200, headers: { "Content-Type": "application/octet-stream" } },
      );
    },
    options,
  );
};

export const getDeleteZoneMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/zones/:id",
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getGetZonesMockHandler = (
  overrideResponse?:
    | ArrayBuffer
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ArrayBuffer> | ArrayBuffer),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/zones",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      const binaryBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetZonesResponseMock();
      return HttpResponse.arrayBuffer(
        binaryBody instanceof ArrayBuffer ? binaryBody : new ArrayBuffer(0),
        { status: 200, headers: { "Content-Type": "application/octet-stream" } },
      );
    },
    options,
  );
};

export const getCreateZoneMockHandler = (
  overrideResponse?:
    | ArrayBuffer
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ArrayBuffer> | ArrayBuffer),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/zones",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      const binaryBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getCreateZoneResponseMock();
      return HttpResponse.arrayBuffer(
        binaryBody instanceof ArrayBuffer ? binaryBody : new ArrayBuffer(0),
        { status: 200, headers: { "Content-Type": "application/octet-stream" } },
      );
    },
    options,
  );
};
export const getOpenAPIDefinitionMock = () => [
  getUpdateZoneMockHandler(),
  getDeleteZoneMockHandler(),
  getGetZonesMockHandler(),
  getCreateZoneMockHandler(),
];
