/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  GetVideosParams,
  UploadVideoBody,
  UploadVideoParams,
} from "../../../models";

import { client } from "../../client";

export type uploadVideoResponse200 = {
  data: Blob;
  status: 200;
};

export type uploadVideoResponseSuccess = uploadVideoResponse200 & {
  headers: Headers;
};
export type uploadVideoResponse = uploadVideoResponseSuccess;

export const getUploadVideoUrl = (params: UploadVideoParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/videos/upload?${stringifiedParams}`
    : `/videos/upload`;
};

export const uploadVideo = async (
  uploadVideoBody: UploadVideoBody,
  params: UploadVideoParams,
  options?: RequestInit,
): Promise<uploadVideoResponse> => {
  const formData = new FormData();
  formData.append(`file`, uploadVideoBody.file);
  formData.append(`details`, JSON.stringify(uploadVideoBody.details));

  return client<uploadVideoResponse>(getUploadVideoUrl(params), {
    ...options,
    method: "POST",
    body: formData,
  });
};

export type getVideosResponse200 = {
  data: Blob;
  status: 200;
};

export type getVideosResponseSuccess = getVideosResponse200 & {
  headers: Headers;
};
export type getVideosResponse = getVideosResponseSuccess;

export const getGetVideosUrl = (params?: GetVideosParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/videos?${stringifiedParams}`
    : `/videos`;
};

export const getVideos = async (
  params?: GetVideosParams,
  options?: RequestInit,
): Promise<getVideosResponse> => {
  return client<getVideosResponse>(getGetVideosUrl(params), {
    ...options,
    method: "GET",
  });
};

export type getVideoMediaResponse200 = {
  data: Blob;
  status: 200;
};

export type getVideoMediaResponseSuccess = getVideoMediaResponse200 & {
  headers: Headers;
};
export type getVideoMediaResponse = getVideoMediaResponseSuccess;

export const getGetVideoMediaUrl = (fileIdentifier: string) => {
  return `/videos/${fileIdentifier}`;
};

export const getVideoMedia = async (
  fileIdentifier: string,
  options?: RequestInit,
): Promise<getVideoMediaResponse> => {
  return client<getVideoMediaResponse>(getGetVideoMediaUrl(fileIdentifier), {
    ...options,
    method: "GET",
  });
};

export type deleteVideoResponse200 = {
  data: Blob;
  status: 200;
};

export type deleteVideoResponseSuccess = deleteVideoResponse200 & {
  headers: Headers;
};
export type deleteVideoResponse = deleteVideoResponseSuccess;

export const getDeleteVideoUrl = (fileIdentifier: string) => {
  return `/videos/${fileIdentifier}`;
};

export const deleteVideo = async (
  fileIdentifier: string,
  options?: RequestInit,
): Promise<deleteVideoResponse> => {
  return client<deleteVideoResponse>(getDeleteVideoUrl(fileIdentifier), {
    ...options,
    method: "DELETE",
  });
};

export type getVideoInfoResponse200 = {
  data: Blob;
  status: 200;
};

export type getVideoInfoResponseSuccess = getVideoInfoResponse200 & {
  headers: Headers;
};
export type getVideoInfoResponse = getVideoInfoResponseSuccess;

export const getGetVideoInfoUrl = (fileIdentifier: string) => {
  return `/videos/${fileIdentifier}/info`;
};

export const getVideoInfo = async (
  fileIdentifier: string,
  options?: RequestInit,
): Promise<getVideoInfoResponse> => {
  return client<getVideoInfoResponse>(getGetVideoInfoUrl(fileIdentifier), {
    ...options,
    method: "GET",
  });
};
