/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  GetVideoSequencesParams,
  GetVideosParams,
  UploadVideo200,
  UploadVideoBody,
  UploadVideoParams,
  VideoSequence,
  VideoSequencePage,
} from "../../../models";

import { client } from "../../client";

export type uploadVideoResponse200 = {
  data: UploadVideo200;
  status: 200;
};

export type uploadVideoResponseSuccess = uploadVideoResponse200 & {
  headers: Headers;
};
export type uploadVideoResponse = uploadVideoResponseSuccess;

export const getUploadVideoUrl = (params: UploadVideoParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/videos/upload?${stringifiedParams}` : `/videos/upload`;
};

export const uploadVideo = async (
  uploadVideoBody: UploadVideoBody,
  params: UploadVideoParams,
  options?: RequestInit,
): Promise<uploadVideoResponse> => {
  const formData = new FormData();
  formData.append(`file`, uploadVideoBody.file);
  formData.append(`details`, JSON.stringify(uploadVideoBody.details));

  return client<uploadVideoResponse>(getUploadVideoUrl(params), {
    ...options,
    method: "POST",
    body: formData,
  });
};

export type getVideosResponse200 = {
  data: Blob;
  status: 200;
};

export type getVideosResponseSuccess = getVideosResponse200 & {
  headers: Headers;
};
export type getVideosResponse = getVideosResponseSuccess;

export const getGetVideosUrl = (params?: GetVideosParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/videos?${stringifiedParams}` : `/videos`;
};

export const getVideos = async (
  params?: GetVideosParams,
  options?: RequestInit,
): Promise<getVideosResponse> => {
  return client<getVideosResponse>(getGetVideosUrl(params), {
    ...options,
    method: "GET",
  });
};

export type getVideoMediaResponse200 = {
  data: Blob;
  status: 200;
};

export type getVideoMediaResponseSuccess = getVideoMediaResponse200 & {
  headers: Headers;
};
export type getVideoMediaResponse = getVideoMediaResponseSuccess;

export const getGetVideoMediaUrl = (fileIdentifier: string) => {
  return `/videos/${fileIdentifier}`;
};

export const getVideoMedia = async (
  fileIdentifier: string,
  options?: RequestInit,
): Promise<getVideoMediaResponse> => {
  return client<getVideoMediaResponse>(getGetVideoMediaUrl(fileIdentifier), {
    ...options,
    method: "GET",
  });
};

export type deleteVideoResponse200 = {
  data: Blob;
  status: 200;
};

export type deleteVideoResponseSuccess = deleteVideoResponse200 & {
  headers: Headers;
};
export type deleteVideoResponse = deleteVideoResponseSuccess;

export const getDeleteVideoUrl = (fileIdentifier: string) => {
  return `/videos/${fileIdentifier}`;
};

export const deleteVideo = async (
  fileIdentifier: string,
  options?: RequestInit,
): Promise<deleteVideoResponse> => {
  return client<deleteVideoResponse>(getDeleteVideoUrl(fileIdentifier), {
    ...options,
    method: "DELETE",
  });
};

export type getVideoDashManifestResponse200 = {
  data: string;
  status: 200;
};

export type getVideoDashManifestResponseSuccess = getVideoDashManifestResponse200 & {
  headers: Headers;
};
export type getVideoDashManifestResponse = getVideoDashManifestResponseSuccess;

export const getGetVideoDashManifestUrl = (fileIdentifier: string) => {
  return `/videos/${fileIdentifier}/manifest.mpd`;
};

export const getVideoDashManifest = async (
  fileIdentifier: string,
  options?: RequestInit,
): Promise<getVideoDashManifestResponse> => {
  return client<getVideoDashManifestResponse>(getGetVideoDashManifestUrl(fileIdentifier), {
    ...options,
    method: "GET",
  });
};

export type getVideoInfoResponse200 = {
  data: Blob;
  status: 200;
};

export type getVideoInfoResponseSuccess = getVideoInfoResponse200 & {
  headers: Headers;
};
export type getVideoInfoResponse = getVideoInfoResponseSuccess;

export const getGetVideoInfoUrl = (fileIdentifier: string) => {
  return `/videos/${fileIdentifier}/info`;
};

export const getVideoInfo = async (
  fileIdentifier: string,
  options?: RequestInit,
): Promise<getVideoInfoResponse> => {
  return client<getVideoInfoResponse>(getGetVideoInfoUrl(fileIdentifier), {
    ...options,
    method: "GET",
  });
};

export type getVideoDashAssetResponse200 = {
  data: Blob;
  status: 200;
};

export type getVideoDashAssetResponseSuccess = getVideoDashAssetResponse200 & {
  headers: Headers;
};
export type getVideoDashAssetResponse = getVideoDashAssetResponseSuccess;

export const getGetVideoDashAssetUrl = (fileIdentifier: string, assetPath: string) => {
  return `/videos/${fileIdentifier}/dash/${assetPath}`;
};

export const getVideoDashAsset = async (
  fileIdentifier: string,
  assetPath: string,
  options?: RequestInit,
): Promise<getVideoDashAssetResponse> => {
  return client<getVideoDashAssetResponse>(getGetVideoDashAssetUrl(fileIdentifier, assetPath), {
    ...options,
    method: "GET",
  });
};

export type getVideoSequencesResponse200 = {
  data: VideoSequencePage;
  status: 200;
};

export type getVideoSequencesResponseSuccess = getVideoSequencesResponse200 & {
  headers: Headers;
};
export type getVideoSequencesResponse = getVideoSequencesResponseSuccess;

export const getGetVideoSequencesUrl = (params?: GetVideoSequencesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/videos/sequences?${stringifiedParams}`
    : `/videos/sequences`;
};

export const getVideoSequences = async (
  params?: GetVideoSequencesParams,
  options?: RequestInit,
): Promise<getVideoSequencesResponse> => {
  return client<getVideoSequencesResponse>(getGetVideoSequencesUrl(params), {
    ...options,
    method: "GET",
  });
};

export type getVideoSequences1Response200 = {
  data: VideoSequence;
  status: 200;
};

export type getVideoSequences1ResponseSuccess = getVideoSequences1Response200 & {
  headers: Headers;
};
export type getVideoSequences1Response = getVideoSequences1ResponseSuccess;

export const getGetVideoSequences1Url = (originId: string) => {
  return `/videos/sequences/${originId}`;
};

export const getVideoSequences1 = async (
  originId: string,
  options?: RequestInit,
): Promise<getVideoSequences1Response> => {
  return client<getVideoSequences1Response>(getGetVideoSequences1Url(originId), {
    ...options,
    method: "GET",
  });
};

export type getSequenceManifestResponse200 = {
  data: string;
  status: 200;
};

export type getSequenceManifestResponseSuccess = getSequenceManifestResponse200 & {
  headers: Headers;
};
export type getSequenceManifestResponse = getSequenceManifestResponseSuccess;

export const getGetSequenceManifestUrl = (originId: string) => {
  return `/videos/sequences/${originId}/manifest.mpd`;
};

export const getSequenceManifest = async (
  originId: string,
  options?: RequestInit,
): Promise<getSequenceManifestResponse> => {
  return client<getSequenceManifestResponse>(getGetSequenceManifestUrl(originId), {
    ...options,
    method: "GET",
  });
};

export type getVideoSequenceInfoResponse200 = {
  data: Blob;
  status: 200;
};

export type getVideoSequenceInfoResponseSuccess = getVideoSequenceInfoResponse200 & {
  headers: Headers;
};
export type getVideoSequenceInfoResponse = getVideoSequenceInfoResponseSuccess;

export const getGetVideoSequenceInfoUrl = (originId: string) => {
  return `/videos/sequences/${originId}/info`;
};

export const getVideoSequenceInfo = async (
  originId: string,
  options?: RequestInit,
): Promise<getVideoSequenceInfoResponse> => {
  return client<getVideoSequenceInfoResponse>(getGetVideoSequenceInfoUrl(originId), {
    ...options,
    method: "GET",
  });
};

export type getSequenceDashAssetResponse200 = {
  data: Blob;
  status: 200;
};

export type getSequenceDashAssetResponseSuccess = getSequenceDashAssetResponse200 & {
  headers: Headers;
};
export type getSequenceDashAssetResponse = getSequenceDashAssetResponseSuccess;

export const getGetSequenceDashAssetUrl = (
  originId: string,
  videoId: string,
  assetPath: string,
) => {
  return `/videos/sequences/${originId}/dash/${videoId}/${assetPath}`;
};

export const getSequenceDashAsset = async (
  originId: string,
  videoId: string,
  assetPath: string,
  options?: RequestInit,
): Promise<getSequenceDashAssetResponse> => {
  return client<getSequenceDashAssetResponse>(
    getGetSequenceDashAssetUrl(originId, videoId, assetPath),
    {
      ...options,
      method: "GET",
    },
  );
};
