/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";


import { orvalAxiosInstance } from "@/lib/orval-axios";
import type { ErrorType, BodyType } from "@/lib/orval-axios";
import type {
  GetVideoSequencesParams,
  GetVideosParams,
  UploadVideo200,
  UploadVideoBody,
  UploadVideoParams,
  VideoSequence,
  VideoSequencePage,
} from "@/types/api";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const uploadVideo = (
  uploadVideoBody: BodyType<UploadVideoBody>,
  params: UploadVideoParams,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  formData.append(`file`, uploadVideoBody.file);
  formData.append(`details`, JSON.stringify(uploadVideoBody.details));

  return orvalAxiosInstance<UploadVideo200>(
    { url: `/videos/upload`, method: "POST", data: formData, params, signal },
    options,
  );
};

export const getUploadVideoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadVideo>>,
    TError,
    { data: BodyType<UploadVideoBody>; params: UploadVideoParams },
    TContext
  >;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof uploadVideo>>,
  TError,
  { data: BodyType<UploadVideoBody>; params: UploadVideoParams },
  TContext
> => {
  const mutationKey = ["uploadVideo"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadVideo>>,
    { data: BodyType<UploadVideoBody>; params: UploadVideoParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return uploadVideo(data, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UploadVideoMutationResult = NonNullable<Awaited<ReturnType<typeof uploadVideo>>>;
export type UploadVideoMutationBody = BodyType<UploadVideoBody>;
export type UploadVideoMutationError = ErrorType<unknown>;

export const useUploadVideo = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof uploadVideo>>,
      TError,
      { data: BodyType<UploadVideoBody>; params: UploadVideoParams },
      TContext
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof uploadVideo>>,
  TError,
  { data: BodyType<UploadVideoBody>; params: UploadVideoParams },
  TContext
> => {
  return useMutation(getUploadVideoMutationOptions(options), queryClient);
};

export const getVideos = (
  params?: GetVideosParams,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<Blob>(
    { url: `/videos`, method: "GET", params, responseType: "blob", signal },
    options,
  );
};

export const getGetVideosInfiniteQueryKey = (params?: GetVideosParams) => {
  return ["infinite", "getVideos", ...(params ? [params] : [])] as const;
};

export const getGetVideosQueryKey = (params?: GetVideosParams) => {
  return ["getVideos", ...(params ? [params] : [])] as const;
};

export const getGetVideosInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getVideos>>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVideosParams,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideos>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVideosInfiniteQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideos>>> = ({ signal }) =>
    getVideos(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getVideos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideosInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getVideos>>>;
export type GetVideosInfiniteQueryError = ErrorType<unknown>;

export function useGetVideosInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideos>>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetVideosParams,
  options: {
    query: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideos>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideos>>,
          TError,
          Awaited<ReturnType<typeof getVideos>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideosInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideos>>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVideosParams,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideos>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideos>>,
          TError,
          Awaited<ReturnType<typeof getVideos>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideosInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideos>>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVideosParams,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideos>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVideosInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideos>>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVideosParams,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideos>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetVideosInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetVideosQueryOptions = <
  TData = Awaited<ReturnType<typeof getVideos>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVideosParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideos>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVideosQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideos>>> = ({ signal }) =>
    getVideos(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getVideos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideosQueryResult = NonNullable<Awaited<ReturnType<typeof getVideos>>>;
export type GetVideosQueryError = ErrorType<unknown>;

export function useGetVideos<
  TData = Awaited<ReturnType<typeof getVideos>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetVideosParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideos>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideos>>,
          TError,
          Awaited<ReturnType<typeof getVideos>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideos<
  TData = Awaited<ReturnType<typeof getVideos>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVideosParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideos>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideos>>,
          TError,
          Awaited<ReturnType<typeof getVideos>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideos<
  TData = Awaited<ReturnType<typeof getVideos>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVideosParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideos>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVideos<
  TData = Awaited<ReturnType<typeof getVideos>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVideosParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideos>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetVideosQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getVideoMedia = (
  fileIdentifier: string,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<Blob>(
    { url: `/videos/${fileIdentifier}`, method: "GET", responseType: "blob", signal },
    options,
  );
};

export const getGetVideoMediaInfiniteQueryKey = (fileIdentifier: string) => {
  return ["infinite", "getVideoMedia", ...(fileIdentifier ? [fileIdentifier] : [])] as const;
};

export const getGetVideoMediaQueryKey = (fileIdentifier: string) => {
  return ["getVideoMedia", ...(fileIdentifier ? [fileIdentifier] : [])] as const;
};

export const getGetVideoMediaInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoMedia>>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoMedia>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVideoMediaInfiniteQueryKey(fileIdentifier);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideoMedia>>> = ({ signal }) =>
    getVideoMedia(fileIdentifier, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!fileIdentifier,
    ...queryOptions,
  } as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoMedia>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetVideoMediaInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideoMedia>>
>;
export type GetVideoMediaInfiniteQueryError = ErrorType<unknown>;

export function useGetVideoMediaInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoMedia>>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoMedia>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoMedia>>,
          TError,
          Awaited<ReturnType<typeof getVideoMedia>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoMediaInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoMedia>>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoMedia>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoMedia>>,
          TError,
          Awaited<ReturnType<typeof getVideoMedia>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoMediaInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoMedia>>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoMedia>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVideoMediaInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoMedia>>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoMedia>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetVideoMediaInfiniteQueryOptions(fileIdentifier, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetVideoMediaQueryOptions = <
  TData = Awaited<ReturnType<typeof getVideoMedia>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoMedia>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVideoMediaQueryKey(fileIdentifier);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideoMedia>>> = ({ signal }) =>
    getVideoMedia(fileIdentifier, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!fileIdentifier, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getVideoMedia>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideoMediaQueryResult = NonNullable<Awaited<ReturnType<typeof getVideoMedia>>>;
export type GetVideoMediaQueryError = ErrorType<unknown>;

export function useGetVideoMedia<
  TData = Awaited<ReturnType<typeof getVideoMedia>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoMedia>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoMedia>>,
          TError,
          Awaited<ReturnType<typeof getVideoMedia>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoMedia<
  TData = Awaited<ReturnType<typeof getVideoMedia>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoMedia>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoMedia>>,
          TError,
          Awaited<ReturnType<typeof getVideoMedia>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoMedia<
  TData = Awaited<ReturnType<typeof getVideoMedia>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoMedia>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVideoMedia<
  TData = Awaited<ReturnType<typeof getVideoMedia>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoMedia>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetVideoMediaQueryOptions(fileIdentifier, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const deleteVideo = (
  fileIdentifier: string,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<Blob>(
    { url: `/videos/${fileIdentifier}`, method: "DELETE", responseType: "blob", signal },
    options,
  );
};

export const getDeleteVideoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteVideo>>,
    TError,
    { fileIdentifier: string },
    TContext
  >;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteVideo>>,
  TError,
  { fileIdentifier: string },
  TContext
> => {
  const mutationKey = ["deleteVideo"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteVideo>>,
    { fileIdentifier: string }
  > = (props) => {
    const { fileIdentifier } = props ?? {};

    return deleteVideo(fileIdentifier, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteVideoMutationResult = NonNullable<Awaited<ReturnType<typeof deleteVideo>>>;

export type DeleteVideoMutationError = ErrorType<unknown>;

export const useDeleteVideo = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteVideo>>,
      TError,
      { fileIdentifier: string },
      TContext
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteVideo>>,
  TError,
  { fileIdentifier: string },
  TContext
> => {
  return useMutation(getDeleteVideoMutationOptions(options), queryClient);
};

export const getVideoDashManifest = (
  fileIdentifier: string,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<string>(
    { url: `/videos/${fileIdentifier}/manifest.mpd`, method: "GET", signal },
    options,
  );
};

export const getGetVideoDashManifestInfiniteQueryKey = (fileIdentifier: string) => {
  return ["infinite", "getVideoDashManifest", ...(fileIdentifier ? [fileIdentifier] : [])] as const;
};

export const getGetVideoDashManifestQueryKey = (fileIdentifier: string) => {
  return ["getVideoDashManifest", ...(fileIdentifier ? [fileIdentifier] : [])] as const;
};

export const getGetVideoDashManifestInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoDashManifest>>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoDashManifest>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetVideoDashManifestInfiniteQueryKey(fileIdentifier);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideoDashManifest>>> = ({ signal }) =>
    getVideoDashManifest(fileIdentifier, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!fileIdentifier,
    ...queryOptions,
  } as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoDashManifest>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetVideoDashManifestInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideoDashManifest>>
>;
export type GetVideoDashManifestInfiniteQueryError = ErrorType<unknown>;

export function useGetVideoDashManifestInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoDashManifest>>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoDashManifest>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoDashManifest>>,
          TError,
          Awaited<ReturnType<typeof getVideoDashManifest>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoDashManifestInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoDashManifest>>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoDashManifest>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoDashManifest>>,
          TError,
          Awaited<ReturnType<typeof getVideoDashManifest>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoDashManifestInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoDashManifest>>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoDashManifest>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVideoDashManifestInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoDashManifest>>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoDashManifest>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetVideoDashManifestInfiniteQueryOptions(fileIdentifier, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetVideoDashManifestQueryOptions = <
  TData = Awaited<ReturnType<typeof getVideoDashManifest>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVideoDashManifest>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVideoDashManifestQueryKey(fileIdentifier);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideoDashManifest>>> = ({ signal }) =>
    getVideoDashManifest(fileIdentifier, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!fileIdentifier, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getVideoDashManifest>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideoDashManifestQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideoDashManifest>>
>;
export type GetVideoDashManifestQueryError = ErrorType<unknown>;

export function useGetVideoDashManifest<
  TData = Awaited<ReturnType<typeof getVideoDashManifest>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVideoDashManifest>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoDashManifest>>,
          TError,
          Awaited<ReturnType<typeof getVideoDashManifest>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoDashManifest<
  TData = Awaited<ReturnType<typeof getVideoDashManifest>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVideoDashManifest>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoDashManifest>>,
          TError,
          Awaited<ReturnType<typeof getVideoDashManifest>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoDashManifest<
  TData = Awaited<ReturnType<typeof getVideoDashManifest>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVideoDashManifest>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVideoDashManifest<
  TData = Awaited<ReturnType<typeof getVideoDashManifest>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVideoDashManifest>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetVideoDashManifestQueryOptions(fileIdentifier, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getVideoInfo = (
  fileIdentifier: string,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<Blob>(
    { url: `/videos/${fileIdentifier}/info`, method: "GET", responseType: "blob", signal },
    options,
  );
};

export const getGetVideoInfoInfiniteQueryKey = (fileIdentifier: string) => {
  return ["infinite", "getVideoInfo", ...(fileIdentifier ? [fileIdentifier] : [])] as const;
};

export const getGetVideoInfoQueryKey = (fileIdentifier: string) => {
  return ["getVideoInfo", ...(fileIdentifier ? [fileIdentifier] : [])] as const;
};

export const getGetVideoInfoInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoInfo>>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoInfo>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVideoInfoInfiniteQueryKey(fileIdentifier);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideoInfo>>> = ({ signal }) =>
    getVideoInfo(fileIdentifier, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!fileIdentifier,
    ...queryOptions,
  } as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoInfo>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetVideoInfoInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getVideoInfo>>>;
export type GetVideoInfoInfiniteQueryError = ErrorType<unknown>;

export function useGetVideoInfoInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoInfo>>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoInfo>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoInfo>>,
          TError,
          Awaited<ReturnType<typeof getVideoInfo>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoInfoInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoInfo>>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoInfo>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoInfo>>,
          TError,
          Awaited<ReturnType<typeof getVideoInfo>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoInfoInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoInfo>>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoInfo>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVideoInfoInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoInfo>>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoInfo>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetVideoInfoInfiniteQueryOptions(fileIdentifier, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetVideoInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof getVideoInfo>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoInfo>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVideoInfoQueryKey(fileIdentifier);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideoInfo>>> = ({ signal }) =>
    getVideoInfo(fileIdentifier, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!fileIdentifier, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getVideoInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideoInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getVideoInfo>>>;
export type GetVideoInfoQueryError = ErrorType<unknown>;

export function useGetVideoInfo<
  TData = Awaited<ReturnType<typeof getVideoInfo>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoInfo>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoInfo>>,
          TError,
          Awaited<ReturnType<typeof getVideoInfo>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoInfo<
  TData = Awaited<ReturnType<typeof getVideoInfo>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoInfo>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoInfo>>,
          TError,
          Awaited<ReturnType<typeof getVideoInfo>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoInfo<
  TData = Awaited<ReturnType<typeof getVideoInfo>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoInfo>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVideoInfo<
  TData = Awaited<ReturnType<typeof getVideoInfo>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoInfo>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetVideoInfoQueryOptions(fileIdentifier, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getVideoDashAsset = (
  fileIdentifier: string,
  assetPath: string,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<Blob>(
    {
      url: `/videos/${fileIdentifier}/dash/${assetPath}`,
      method: "GET",
      responseType: "blob",
      signal,
    },
    options,
  );
};

export const getGetVideoDashAssetInfiniteQueryKey = (fileIdentifier: string, assetPath: string) => {
  return [
    "infinite",
    "getVideoDashAsset",
    ...(assetPath ? [assetPath] : []),
    ...(fileIdentifier ? [fileIdentifier] : []),
  ] as const;
};

export const getGetVideoDashAssetQueryKey = (fileIdentifier: string, assetPath: string) => {
  return [
    "getVideoDashAsset",
    ...(assetPath ? [assetPath] : []),
    ...(fileIdentifier ? [fileIdentifier] : []),
  ] as const;
};

export const getGetVideoDashAssetInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoDashAsset>>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  assetPath: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoDashAsset>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetVideoDashAssetInfiniteQueryKey(fileIdentifier, assetPath);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideoDashAsset>>> = ({ signal }) =>
    getVideoDashAsset(fileIdentifier, assetPath, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(fileIdentifier && assetPath),
    ...queryOptions,
  } as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoDashAsset>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetVideoDashAssetInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideoDashAsset>>
>;
export type GetVideoDashAssetInfiniteQueryError = ErrorType<unknown>;

export function useGetVideoDashAssetInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoDashAsset>>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  assetPath: string,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoDashAsset>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoDashAsset>>,
          TError,
          Awaited<ReturnType<typeof getVideoDashAsset>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoDashAssetInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoDashAsset>>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  assetPath: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoDashAsset>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoDashAsset>>,
          TError,
          Awaited<ReturnType<typeof getVideoDashAsset>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoDashAssetInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoDashAsset>>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  assetPath: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoDashAsset>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVideoDashAssetInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoDashAsset>>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  assetPath: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoDashAsset>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetVideoDashAssetInfiniteQueryOptions(fileIdentifier, assetPath, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetVideoDashAssetQueryOptions = <
  TData = Awaited<ReturnType<typeof getVideoDashAsset>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  assetPath: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoDashAsset>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetVideoDashAssetQueryKey(fileIdentifier, assetPath);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideoDashAsset>>> = ({ signal }) =>
    getVideoDashAsset(fileIdentifier, assetPath, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(fileIdentifier && assetPath),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getVideoDashAsset>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetVideoDashAssetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideoDashAsset>>
>;
export type GetVideoDashAssetQueryError = ErrorType<unknown>;

export function useGetVideoDashAsset<
  TData = Awaited<ReturnType<typeof getVideoDashAsset>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  assetPath: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoDashAsset>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoDashAsset>>,
          TError,
          Awaited<ReturnType<typeof getVideoDashAsset>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoDashAsset<
  TData = Awaited<ReturnType<typeof getVideoDashAsset>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  assetPath: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoDashAsset>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoDashAsset>>,
          TError,
          Awaited<ReturnType<typeof getVideoDashAsset>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoDashAsset<
  TData = Awaited<ReturnType<typeof getVideoDashAsset>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  assetPath: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoDashAsset>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVideoDashAsset<
  TData = Awaited<ReturnType<typeof getVideoDashAsset>>,
  TError = ErrorType<unknown>,
>(
  fileIdentifier: string,
  assetPath: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoDashAsset>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetVideoDashAssetQueryOptions(fileIdentifier, assetPath, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getVideoSequences = (
  params?: GetVideoSequencesParams,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<VideoSequencePage>(
    { url: `/videos/sequences`, method: "GET", params, signal },
    options,
  );
};

export const getGetVideoSequencesInfiniteQueryKey = (params?: GetVideoSequencesParams) => {
  return ["infinite", "getVideoSequences", ...(params ? [params] : [])] as const;
};

export const getGetVideoSequencesQueryKey = (params?: GetVideoSequencesParams) => {
  return ["getVideoSequences", ...(params ? [params] : [])] as const;
};

export const getGetVideoSequencesInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoSequences>>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVideoSequencesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoSequences>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVideoSequencesInfiniteQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideoSequences>>> = ({ signal }) =>
    getVideoSequences(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getVideoSequences>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideoSequencesInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideoSequences>>
>;
export type GetVideoSequencesInfiniteQueryError = ErrorType<unknown>;

export function useGetVideoSequencesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoSequences>>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetVideoSequencesParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoSequences>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoSequences>>,
          TError,
          Awaited<ReturnType<typeof getVideoSequences>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoSequencesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoSequences>>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVideoSequencesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoSequences>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoSequences>>,
          TError,
          Awaited<ReturnType<typeof getVideoSequences>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoSequencesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoSequences>>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVideoSequencesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoSequences>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVideoSequencesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoSequences>>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVideoSequencesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoSequences>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetVideoSequencesInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetVideoSequencesQueryOptions = <
  TData = Awaited<ReturnType<typeof getVideoSequences>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVideoSequencesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoSequences>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVideoSequencesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideoSequences>>> = ({ signal }) =>
    getVideoSequences(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getVideoSequences>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideoSequencesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideoSequences>>
>;
export type GetVideoSequencesQueryError = ErrorType<unknown>;

export function useGetVideoSequences<
  TData = Awaited<ReturnType<typeof getVideoSequences>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetVideoSequencesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoSequences>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoSequences>>,
          TError,
          Awaited<ReturnType<typeof getVideoSequences>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoSequences<
  TData = Awaited<ReturnType<typeof getVideoSequences>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVideoSequencesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoSequences>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoSequences>>,
          TError,
          Awaited<ReturnType<typeof getVideoSequences>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoSequences<
  TData = Awaited<ReturnType<typeof getVideoSequences>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVideoSequencesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoSequences>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVideoSequences<
  TData = Awaited<ReturnType<typeof getVideoSequences>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVideoSequencesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoSequences>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetVideoSequencesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getVideoSequence = (
  originId: string,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<VideoSequence>(
    { url: `/videos/sequences/${originId}`, method: "GET", signal },
    options,
  );
};

export const getGetVideoSequenceInfiniteQueryKey = (originId: string) => {
  return ["infinite", "getVideoSequence", ...(originId ? [originId] : [])] as const;
};

export const getGetVideoSequenceQueryKey = (originId: string) => {
  return ["getVideoSequence", ...(originId ? [originId] : [])] as const;
};

export const getGetVideoSequenceInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoSequence>>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoSequence>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVideoSequenceInfiniteQueryKey(originId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideoSequence>>> = ({ signal }) =>
    getVideoSequence(originId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!originId, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getVideoSequence>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideoSequenceInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideoSequence>>
>;
export type GetVideoSequenceInfiniteQueryError = ErrorType<unknown>;

export function useGetVideoSequenceInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoSequence>>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoSequence>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoSequence>>,
          TError,
          Awaited<ReturnType<typeof getVideoSequence>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoSequenceInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoSequence>>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoSequence>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoSequence>>,
          TError,
          Awaited<ReturnType<typeof getVideoSequence>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoSequenceInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoSequence>>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoSequence>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVideoSequenceInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoSequence>>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoSequence>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetVideoSequenceInfiniteQueryOptions(originId, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetVideoSequenceQueryOptions = <
  TData = Awaited<ReturnType<typeof getVideoSequence>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoSequence>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVideoSequenceQueryKey(originId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideoSequence>>> = ({ signal }) =>
    getVideoSequence(originId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!originId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getVideoSequence>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideoSequenceQueryResult = NonNullable<Awaited<ReturnType<typeof getVideoSequence>>>;
export type GetVideoSequenceQueryError = ErrorType<unknown>;

export function useGetVideoSequence<
  TData = Awaited<ReturnType<typeof getVideoSequence>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoSequence>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoSequence>>,
          TError,
          Awaited<ReturnType<typeof getVideoSequence>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoSequence<
  TData = Awaited<ReturnType<typeof getVideoSequence>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoSequence>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoSequence>>,
          TError,
          Awaited<ReturnType<typeof getVideoSequence>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoSequence<
  TData = Awaited<ReturnType<typeof getVideoSequence>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoSequence>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVideoSequence<
  TData = Awaited<ReturnType<typeof getVideoSequence>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoSequence>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetVideoSequenceQueryOptions(originId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getSequenceManifest = (
  originId: string,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<string>(
    { url: `/videos/sequences/${originId}/manifest.mpd`, method: "GET", signal },
    options,
  );
};

export const getGetSequenceManifestInfiniteQueryKey = (originId: string) => {
  return ["infinite", "getSequenceManifest", ...(originId ? [originId] : [])] as const;
};

export const getGetSequenceManifestQueryKey = (originId: string) => {
  return ["getSequenceManifest", ...(originId ? [originId] : [])] as const;
};

export const getGetSequenceManifestInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getSequenceManifest>>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSequenceManifest>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSequenceManifestInfiniteQueryKey(originId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSequenceManifest>>> = ({ signal }) =>
    getSequenceManifest(originId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!originId, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getSequenceManifest>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSequenceManifestInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSequenceManifest>>
>;
export type GetSequenceManifestInfiniteQueryError = ErrorType<unknown>;

export function useGetSequenceManifestInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSequenceManifest>>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSequenceManifest>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSequenceManifest>>,
          TError,
          Awaited<ReturnType<typeof getSequenceManifest>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSequenceManifestInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSequenceManifest>>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSequenceManifest>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSequenceManifest>>,
          TError,
          Awaited<ReturnType<typeof getSequenceManifest>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSequenceManifestInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSequenceManifest>>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSequenceManifest>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetSequenceManifestInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSequenceManifest>>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSequenceManifest>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSequenceManifestInfiniteQueryOptions(originId, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetSequenceManifestQueryOptions = <
  TData = Awaited<ReturnType<typeof getSequenceManifest>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSequenceManifest>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSequenceManifestQueryKey(originId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSequenceManifest>>> = ({ signal }) =>
    getSequenceManifest(originId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!originId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSequenceManifest>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSequenceManifestQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSequenceManifest>>
>;
export type GetSequenceManifestQueryError = ErrorType<unknown>;

export function useGetSequenceManifest<
  TData = Awaited<ReturnType<typeof getSequenceManifest>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSequenceManifest>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSequenceManifest>>,
          TError,
          Awaited<ReturnType<typeof getSequenceManifest>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSequenceManifest<
  TData = Awaited<ReturnType<typeof getSequenceManifest>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSequenceManifest>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSequenceManifest>>,
          TError,
          Awaited<ReturnType<typeof getSequenceManifest>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSequenceManifest<
  TData = Awaited<ReturnType<typeof getSequenceManifest>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSequenceManifest>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetSequenceManifest<
  TData = Awaited<ReturnType<typeof getSequenceManifest>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSequenceManifest>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSequenceManifestQueryOptions(originId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getVideoSequenceInfo = (
  originId: string,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<Blob>(
    { url: `/videos/sequences/${originId}/info`, method: "GET", responseType: "blob", signal },
    options,
  );
};

export const getGetVideoSequenceInfoInfiniteQueryKey = (originId: string) => {
  return ["infinite", "getVideoSequenceInfo", ...(originId ? [originId] : [])] as const;
};

export const getGetVideoSequenceInfoQueryKey = (originId: string) => {
  return ["getVideoSequenceInfo", ...(originId ? [originId] : [])] as const;
};

export const getGetVideoSequenceInfoInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoSequenceInfo>>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoSequenceInfo>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVideoSequenceInfoInfiniteQueryKey(originId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideoSequenceInfo>>> = ({ signal }) =>
    getVideoSequenceInfo(originId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!originId, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getVideoSequenceInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideoSequenceInfoInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideoSequenceInfo>>
>;
export type GetVideoSequenceInfoInfiniteQueryError = ErrorType<unknown>;

export function useGetVideoSequenceInfoInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoSequenceInfo>>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoSequenceInfo>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoSequenceInfo>>,
          TError,
          Awaited<ReturnType<typeof getVideoSequenceInfo>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoSequenceInfoInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoSequenceInfo>>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoSequenceInfo>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoSequenceInfo>>,
          TError,
          Awaited<ReturnType<typeof getVideoSequenceInfo>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoSequenceInfoInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoSequenceInfo>>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoSequenceInfo>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVideoSequenceInfoInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getVideoSequenceInfo>>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVideoSequenceInfo>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetVideoSequenceInfoInfiniteQueryOptions(originId, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetVideoSequenceInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof getVideoSequenceInfo>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVideoSequenceInfo>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVideoSequenceInfoQueryKey(originId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideoSequenceInfo>>> = ({ signal }) =>
    getVideoSequenceInfo(originId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!originId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getVideoSequenceInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVideoSequenceInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideoSequenceInfo>>
>;
export type GetVideoSequenceInfoQueryError = ErrorType<unknown>;

export function useGetVideoSequenceInfo<
  TData = Awaited<ReturnType<typeof getVideoSequenceInfo>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVideoSequenceInfo>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoSequenceInfo>>,
          TError,
          Awaited<ReturnType<typeof getVideoSequenceInfo>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoSequenceInfo<
  TData = Awaited<ReturnType<typeof getVideoSequenceInfo>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVideoSequenceInfo>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoSequenceInfo>>,
          TError,
          Awaited<ReturnType<typeof getVideoSequenceInfo>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetVideoSequenceInfo<
  TData = Awaited<ReturnType<typeof getVideoSequenceInfo>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVideoSequenceInfo>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVideoSequenceInfo<
  TData = Awaited<ReturnType<typeof getVideoSequenceInfo>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVideoSequenceInfo>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetVideoSequenceInfoQueryOptions(originId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getSequenceDashAsset = (
  originId: string,
  videoId: string,
  assetPath: string,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<Blob>(
    {
      url: `/videos/sequences/${originId}/dash/${videoId}/${assetPath}`,
      method: "GET",
      responseType: "blob",
      signal,
    },
    options,
  );
};

export const getGetSequenceDashAssetInfiniteQueryKey = (
  originId: string,
  videoId: string,
  assetPath: string,
) => {
  return [
    "infinite",
    "getSequenceDashAsset",
    ...(assetPath ? [assetPath] : []),
    ...(videoId ? [videoId] : []),
    ...(originId ? [originId] : []),
  ] as const;
};

export const getGetSequenceDashAssetQueryKey = (
  originId: string,
  videoId: string,
  assetPath: string,
) => {
  return [
    "getSequenceDashAsset",
    ...(assetPath ? [assetPath] : []),
    ...(videoId ? [videoId] : []),
    ...(originId ? [originId] : []),
  ] as const;
};

export const getGetSequenceDashAssetInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getSequenceDashAsset>>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  videoId: string,
  assetPath: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSequenceDashAsset>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetSequenceDashAssetInfiniteQueryKey(originId, videoId, assetPath);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSequenceDashAsset>>> = ({ signal }) =>
    getSequenceDashAsset(originId, videoId, assetPath, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(originId && videoId && assetPath),
    ...queryOptions,
  } as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSequenceDashAsset>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetSequenceDashAssetInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSequenceDashAsset>>
>;
export type GetSequenceDashAssetInfiniteQueryError = ErrorType<unknown>;

export function useGetSequenceDashAssetInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSequenceDashAsset>>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  videoId: string,
  assetPath: string,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSequenceDashAsset>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSequenceDashAsset>>,
          TError,
          Awaited<ReturnType<typeof getSequenceDashAsset>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSequenceDashAssetInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSequenceDashAsset>>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  videoId: string,
  assetPath: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSequenceDashAsset>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSequenceDashAsset>>,
          TError,
          Awaited<ReturnType<typeof getSequenceDashAsset>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSequenceDashAssetInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSequenceDashAsset>>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  videoId: string,
  assetPath: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSequenceDashAsset>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetSequenceDashAssetInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSequenceDashAsset>>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  videoId: string,
  assetPath: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSequenceDashAsset>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSequenceDashAssetInfiniteQueryOptions(
    originId,
    videoId,
    assetPath,
    options,
  );

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetSequenceDashAssetQueryOptions = <
  TData = Awaited<ReturnType<typeof getSequenceDashAsset>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  videoId: string,
  assetPath: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSequenceDashAsset>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetSequenceDashAssetQueryKey(originId, videoId, assetPath);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSequenceDashAsset>>> = ({ signal }) =>
    getSequenceDashAsset(originId, videoId, assetPath, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(originId && videoId && assetPath),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getSequenceDashAsset>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetSequenceDashAssetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSequenceDashAsset>>
>;
export type GetSequenceDashAssetQueryError = ErrorType<unknown>;

export function useGetSequenceDashAsset<
  TData = Awaited<ReturnType<typeof getSequenceDashAsset>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  videoId: string,
  assetPath: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSequenceDashAsset>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSequenceDashAsset>>,
          TError,
          Awaited<ReturnType<typeof getSequenceDashAsset>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSequenceDashAsset<
  TData = Awaited<ReturnType<typeof getSequenceDashAsset>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  videoId: string,
  assetPath: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSequenceDashAsset>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSequenceDashAsset>>,
          TError,
          Awaited<ReturnType<typeof getSequenceDashAsset>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSequenceDashAsset<
  TData = Awaited<ReturnType<typeof getSequenceDashAsset>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  videoId: string,
  assetPath: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSequenceDashAsset>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetSequenceDashAsset<
  TData = Awaited<ReturnType<typeof getSequenceDashAsset>>,
  TError = ErrorType<unknown>,
>(
  originId: string,
  videoId: string,
  assetPath: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSequenceDashAsset>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSequenceDashAssetQueryOptions(originId, videoId, assetPath, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
