/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ActionClassThresholds } from "./action-class-thresholds";

export interface ActionClass {
  name?: string;
  template?: string;
  thresholds?: ActionClassThresholds;
  warnings?: string[];
}
