/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ActionClass } from "./action-class";
import type { Crowd } from "./crowd";
import type { Zone } from "./zone";

export interface DetectorConfigDTO {
  version?: string;
  zones?: Zone[];
  crowd?: Crowd;
  action_classes?: ActionClass[];
}
