/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ForbiddenZoneDTO {
  id?: number;
  name?: string;
  policy?: string;
  points?: number[][];
  active?: boolean;
  reference_video_id?: string;
  aspect_ratio?: number;
}
