/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ForbiddenZoneRequest {
  /** @minLength 1 */
  name: string;
  points: number[][];
  reference_video_id?: string;
  aspect_ratio?: number;
}
