/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetVideosParams = {
  sort?: string[];
  /**
   * @minimum 1
   */
  size?: number;
  /**
   * @minimum 0
   */
  page?: number;
  from?: string;
  to?: string;
};
