/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export * from "./action-class-thresholds";
export * from "./action-class";
export * from "./add-detection-template200";
export * from "./create-detection-template-request";
export * from "./crowd";
export * from "./delete-detection-template-params";
export * from "./delete-detection-template200";
export * from "./delete-video-sequence200";
export * from "./delete-video200";
export * from "./detection-rule-dt-o";
export * from "./detection-timestamp";
export * from "./detection-vector-dt-o";
export * from "./detector-config-dt-o";
export * from "./edit-detection-template-request";
export * from "./edit-detection-template200";
export * from "./event-detection";
export * from "./forbidden-zone-dt-o";
export * from "./forbidden-zone-request";
export * from "./get-detected-elements200";
export * from "./get-detection-templates-params";
export * from "./get-detection-templates200";
export * from "./get-sequence-dash-asset200";
export * from "./get-video-dash-asset200";
export * from "./get-video-info200";
export * from "./get-video-sequence-info200";
export * from "./get-video-sequences-params";
export * from "./get-videos-params";
export * from "./get-videos200";
export * from "./object-detection";
export * from "./object-detections";
export * from "./pageable";
export * from "./resource-region";
export * from "./upload-video-body";
export * from "./upload-video-params";
export * from "./upload-video200";
export * from "./video-details-request-body";
export * from "./video-sequence-page-page";
export * from "./video-sequence-page";
export * from "./video-sequence-part";
export * from "./video-sequence";
export * from "./zone";
