/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DetectionTimestamp } from "./detection-timestamp";
import type { ObjectDetection } from "./object-detection";

export interface ObjectDetections {
  objects: ObjectDetection[];
  timestamp?: DetectionTimestamp;
}
