/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface VideoSequencePart {
  id: string;
  name: string;
  description?: string | null;
  upload_date: string;
  continuation_of?: string | null;
}
