/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { VideoSequencePart } from "./video-sequence-part";

export interface VideoSequence {
  origin_id: string;
  sequence_upload_date: string;
  parts: VideoSequencePart[];
}
