/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EventDetection } from "./event-detection";
import type { ObjectDetections } from "./object-detections";

export interface VideoDetailsRequestBody {
  events?: EventDetection[];
  detections?: ObjectDetections[];
}
