/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EventDetection } from "./eventDetection";
import type { ObjectDetections } from "./objectDetections";

export interface Details {
  events?: EventDetection[];
  detections?: ObjectDetections[];
}
