/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface DetectionRuleDTO {
  count?: number;
  range?: boolean;
  element_name: string;
  count_from?: number;
  count_to?: number;
}
