/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DetectionRuleDTO } from "./detectionRuleDTO";

export interface DetectionVectorDTO {
  vector_id?: number;
  /** @minItems 1 */
  rules: DetectionRuleDTO[];
}
