/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DetectionVectorDTO } from "./detectionVectorDTO";

export interface EditDetectionTemplateRequest {
  name: string;
  new_name?: string;
  /** @minItems 1 */
  vectors: DetectionVectorDTO[];
}
