/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DetectionTimestamp } from "./detectionTimestamp";

export interface EventDetection {
  /** @minLength 1 */
  label: string;
  timestamp?: DetectionTimestamp;
}
