/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Pageable } from "./pageable";

export type GetVideosParams = {
  pageable: Pageable;
  from?: string;
  to?: string;
};
