/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export * from "./addDetectionTemplate200";
export * from "./createDetectionTemplateRequest";
export * from "./deleteDetectionTemplate200";
export * from "./deleteDetectionTemplateParams";
export * from "./deleteVideo200";
export * from "./details";
export * from "./detectionRuleDTO";
export * from "./detectionTimestamp";
export * from "./detectionVectorDTO";
export * from "./editDetectionTemplate200";
export * from "./editDetectionTemplateRequest";
export * from "./eventDetection";
export * from "./getDetectedElements200";
export * from "./getDetectionTemplates200";
export * from "./getDetectionTemplatesParams";
export * from "./getVideoInfo200";
export * from "./getVideos200";
export * from "./getVideosParams";
export * from "./objectDetection";
export * from "./objectDetections";
export * from "./pageable";
export * from "./resourceRegion";
export * from "./uploadVideo200";
export * from "./uploadVideoBody";
export * from "./uploadVideoParams";
