/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DetectionTimestamp } from "./detectionTimestamp";
import type { ObjectDetection } from "./objectDetection";

export interface ObjectDetections {
  objects: ObjectDetection[];
  timestamp?: DetectionTimestamp;
}
