/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ObjectDetection {
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  count?: number;
}
