/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Details } from "./details";

export type UploadVideoBody = {
  file: Blob;
  details: Details;
};
