/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { VideoSequence } from "./videoSequence";
import type { VideoSequencePagePage } from "./videoSequencePagePage";

export interface VideoSequencePage {
  content: VideoSequence[];
  page: VideoSequencePagePage;
}
