/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  CreateDetectionTemplateRequest,
  DeleteDetectionTemplateParams,
  EditDetectionTemplateRequest,
  GetDetectionTemplatesParams,
} from "../../../models";

import { client } from "../../client";

export type getDetectionTemplatesResponse200 = {
  data: Blob;
  status: 200;
};

export type getDetectionTemplatesResponseSuccess =
  getDetectionTemplatesResponse200 & {
    headers: Headers;
  };
export type getDetectionTemplatesResponse =
  getDetectionTemplatesResponseSuccess;

export const getGetDetectionTemplatesUrl = (
  params?: GetDetectionTemplatesParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/rules?${stringifiedParams}`
    : `/rules`;
};

export const getDetectionTemplates = async (
  params?: GetDetectionTemplatesParams,
  options?: RequestInit,
): Promise<getDetectionTemplatesResponse> => {
  return client<getDetectionTemplatesResponse>(
    getGetDetectionTemplatesUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export type editDetectionTemplateResponse200 = {
  data: Blob;
  status: 200;
};

export type editDetectionTemplateResponseSuccess =
  editDetectionTemplateResponse200 & {
    headers: Headers;
  };
export type editDetectionTemplateResponse =
  editDetectionTemplateResponseSuccess;

export const getEditDetectionTemplateUrl = () => {
  return `/rules`;
};

export const editDetectionTemplate = async (
  editDetectionTemplateRequest: EditDetectionTemplateRequest,
  options?: RequestInit,
): Promise<editDetectionTemplateResponse> => {
  return client<editDetectionTemplateResponse>(getEditDetectionTemplateUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(editDetectionTemplateRequest),
  });
};

export type addDetectionTemplateResponse200 = {
  data: Blob;
  status: 200;
};

export type addDetectionTemplateResponseSuccess =
  addDetectionTemplateResponse200 & {
    headers: Headers;
  };
export type addDetectionTemplateResponse = addDetectionTemplateResponseSuccess;

export const getAddDetectionTemplateUrl = () => {
  return `/rules`;
};

export const addDetectionTemplate = async (
  createDetectionTemplateRequest: CreateDetectionTemplateRequest,
  options?: RequestInit,
): Promise<addDetectionTemplateResponse> => {
  return client<addDetectionTemplateResponse>(getAddDetectionTemplateUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createDetectionTemplateRequest),
  });
};

export type deleteDetectionTemplateResponse200 = {
  data: Blob;
  status: 200;
};

export type deleteDetectionTemplateResponseSuccess =
  deleteDetectionTemplateResponse200 & {
    headers: Headers;
  };
export type deleteDetectionTemplateResponse =
  deleteDetectionTemplateResponseSuccess;

export const getDeleteDetectionTemplateUrl = (
  params: DeleteDetectionTemplateParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/rules/?${stringifiedParams}`
    : `/rules/`;
};

export const deleteDetectionTemplate = async (
  params: DeleteDetectionTemplateParams,
  options?: RequestInit,
): Promise<deleteDetectionTemplateResponse> => {
  return client<deleteDetectionTemplateResponse>(
    getDeleteDetectionTemplateUrl(params),
    {
      ...options,
      method: "DELETE",
    },
  );
};
